version: '3.9'

services:
  db:
    image: postgres:14.3
    ports:
      - '5431:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '1837099'
      POSTGRES_DB: 'api_async'